#!/usr/bin/env bash
# JK2MV (Jedi Outcast) Pterodactyl runtime entrypoint.
#
# This entrypoint is intentionally separate from the TaystJK runtime
# entrypoint (scripts/entrypoint.sh) and shares no state with it.
# It only handles the JK2MV dedicated server.
set -euo pipefail

JK2MV_IMAGE_ROOT="${JK2MV_IMAGE_ROOT:-/opt/jk2mv}"
JK2MV_IMAGE_BINARY="${JK2MV_IMAGE_ROOT}/jk2mvded"
JK2MV_IMAGE_BASE_DIR="${JK2MV_IMAGE_ROOT}/base"

CONTAINER_HOME="${HOME:-/home/container}"
CONTAINER_BASE_DIR="${CONTAINER_HOME}/base"
CONTAINER_LOGS_DIR="${CONTAINER_HOME}/logs"
CONTAINER_CONFIG_DIR="${CONTAINER_HOME}/config"
CONTAINER_BINARY="${CONTAINER_HOME}/jk2mvded"
CONTAINER_SERVER_CFG="${CONTAINER_BASE_DIR}/server.cfg"

SERVER_PORT="${SERVER_PORT:-28070}"
SERVER_CONFIG="${SERVER_CONFIG:-server.cfg}"
JK2MV_SERVER_VERSION="${JK2MV_SERVER_VERSION:-1.04}"

cd "${CONTAINER_HOME}"

mkdir -p "${CONTAINER_BASE_DIR}" "${CONTAINER_LOGS_DIR}" "${CONTAINER_CONFIG_DIR}"

# Install / refresh the JK2MV dedicated binary into the container home if missing.
# We never overwrite a binary the operator placed themselves.
if [[ ! -e "${CONTAINER_BINARY}" ]]; then
    if [[ -x "${JK2MV_IMAGE_BINARY}" || -f "${JK2MV_IMAGE_BINARY}" ]]; then
        cp -n "${JK2MV_IMAGE_BINARY}" "${CONTAINER_BINARY}"
        chmod +x "${CONTAINER_BINARY}"
        printf '[jk2mv-entrypoint] installed jk2mvded -> %s\n' "${CONTAINER_BINARY}"
    else
        printf '[jk2mv-entrypoint] WARNING: image binary %s not found\n' "${JK2MV_IMAGE_BINARY}" >&2
    fi
fi

# Copy JK2MV's own free base assets. cp -n guarantees we never overwrite
# operator-uploaded files (including the legally owned Raven assets).
if [[ -f "${JK2MV_IMAGE_BASE_DIR}/assetsmv.pk3" ]]; then
    cp -n "${JK2MV_IMAGE_BASE_DIR}/assetsmv.pk3" "${CONTAINER_BASE_DIR}/assetsmv.pk3" || true
fi
if [[ -f "${JK2MV_IMAGE_BASE_DIR}/assetsmv2.pk3" ]]; then
    cp -n "${JK2MV_IMAGE_BASE_DIR}/assetsmv2.pk3" "${CONTAINER_BASE_DIR}/assetsmv2.pk3" || true
fi

# Defensive sanity check: this runtime must NEVER overwrite the operator's
# legally owned Raven Jedi Outcast base assets. We only inspect them.
RAVEN_ASSETS=(assets0.pk3 assets1.pk3 assets2.pk3 assets5.pk3)
present_raven=()
missing_raven=()
for asset in "${RAVEN_ASSETS[@]}"; do
    if [[ -f "${CONTAINER_BASE_DIR}/${asset}" ]]; then
        present_raven+=("${asset}")
    else
        missing_raven+=("${asset}")
    fi
done

# Write a minimal default server.cfg only when the operator has not provided one.
if [[ ! -f "${CONTAINER_SERVER_CFG}" ]]; then
    cat > "${CONTAINER_SERVER_CFG}" <<'CFG'
// Default JK2MV server.cfg generated by the JK2MV Pterodactyl runtime.
// Edit this file to customise your server. It will not be regenerated
// once it exists.
seta sv_hostname "^7JKN^1|^7JK2MV Server"
seta rconPassword "change_me"
seta sv_maxclients "16"
seta sv_privateClients "0"
seta sv_pure "1"
seta mv_serverversion "1.04"
seta g_log "server.log"
seta logfile "2"
map ffa_bespin
CFG
    printf '[jk2mv-entrypoint] wrote default server.cfg -> %s\n' "${CONTAINER_SERVER_CFG}"
fi

# Startup summary.
printf '\n'
printf '========================================================\n'
printf ' Mode:                 Jedi Outcast JK2MV\n'
printf ' Binary:               %s\n' "${CONTAINER_BINARY}"
printf ' Port (SERVER_PORT):   %s\n' "${SERVER_PORT}"
printf ' Config (SERVER_CONFIG): %s\n' "${SERVER_CONFIG}"
printf ' JK2MV server version: %s\n' "${JK2MV_SERVER_VERSION}"
if (( ${#present_raven[@]} > 0 )); then
    printf ' Raven assets present: %s\n' "${present_raven[*]}"
else
    printf ' Raven assets present: (none)\n'
fi
if (( ${#missing_raven[@]} > 0 )); then
    printf ' Raven assets missing: %s\n' "${missing_raven[*]}"
fi
if [[ -f "${CONTAINER_BASE_DIR}/assetsmv.pk3" ]]; then
    printf ' JK2MV assets:         assetsmv.pk3 OK\n'
else
    printf ' JK2MV assets:         assetsmv.pk3 MISSING\n'
fi
if [[ -f "${CONTAINER_BASE_DIR}/assetsmv2.pk3" ]]; then
    printf ' JK2MV assets:         assetsmv2.pk3 OK\n'
else
    printf ' JK2MV assets:         assetsmv2.pk3 MISSING\n'
fi
printf '========================================================\n\n'

exec "$@"
